# Lab 2 exercise 4


In [370]:
import pandas as pd
import numpy as np

In [371]:
t1 = pd.read_csv('data/13.1.csv', usecols=[0,1], encoding='latin-1')
t1.columns = ['label','body']
t1['label'] = t1['label'].replace(["no","yes"],[0,1])
# t1 = t1.values
t2 = pd.read_csv('data/13.10.csv', usecols=[0,1], encoding='latin-1')
t2.columns = ['label','body']
t2['label'] = t2['label'].replace(["no","yes"],[0,1])
# t2 = t2.values
t3 = pd.read_csv('data/IAML.csv', usecols=[0,1], encoding='latin-1')
t3.columns = ['label','body']
t3['label'] = t3['label'].replace(["ham","spam"],[0,1])
# t3 = t3.values

# Pre-Processing

In [372]:
t1['body'] = t1.body.map(lambda x: x.lower())
t1['body'] = t1.body.str.replace('[^\w\s]', '')
t1

label                                 body
0      1              chinese beijing chinese
1      1             chinese chinese shanghai
2      1                        chinese macao
3      0                  tokyo japan chinese
4      1  chinese chinese chinese tokyo japan

In [373]:
t2['body'] = t2.body.map(lambda x: x.lower())
t2['body'] = t2.body.str.replace('[^\w\s]', '')
t2

label                   body
0      1          taipei taiwan
1      1  macao taiwan shanghai
2      0          japan sapporo
3      0   sapporo osaka taiwan
4      0  taiwan taiwan sapporo

In [374]:
t3['body'] = t3.body.map(lambda x: x.lower())
t3['body'] = t3.body.str.replace('[^\w\s]', '')
t3

label                   body
0      1  send us your password
1      0    send us your review
2      0   review your password
3      1              review us
4      1     send your password
5      1   send us your account
6      0          review us now

In [375]:
import nltk
nltk.download('punkt')

t1['body'] = t1['body'].apply(nltk.word_tokenize)
t1.head()

[nltk_data] Downloading package punkt to /home/mike/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


label                                       body
0      1                [chinese, beijing, chinese]
1      1               [chinese, chinese, shanghai]
2      1                           [chinese, macao]
3      0                    [tokyo, japan, chinese]
4      1  [chinese, chinese, chinese, tokyo, japan]

In [376]:
t2['body'] = t2['body'].apply(nltk.word_tokenize)
t2.head()

label                       body
0      1           [taipei, taiwan]
1      1  [macao, taiwan, shanghai]
2      0           [japan, sapporo]
3      0   [sapporo, osaka, taiwan]
4      0  [taiwan, taiwan, sapporo]

In [377]:
t3['body'] = t3['body'].apply(nltk.word_tokenize)
t3

label                        body
0      1  [send, us, your, password]
1      0    [send, us, your, review]
2      0    [review, your, password]
3      1                [review, us]
4      1      [send, your, password]
5      1   [send, us, your, account]
6      0           [review, us, now]

In [378]:
from nltk.stem import PorterStemmer
stemmer = PorterStemmer()

In [379]:
t1['body'] = t1['body'].apply(lambda x: [stemmer.stem(y) for y in x])
t1.head()

label                                    body
0      1                  [chines, beij, chines]
1      1              [chines, chines, shanghai]
2      1                         [chines, macao]
3      0                  [tokyo, japan, chines]
4      1  [chines, chines, chines, tokyo, japan]

In [380]:
t2['body'] = t2['body'].apply(lambda x: [stemmer.stem(y) for y in x])
t2.head()

label                       body
0      1           [taipei, taiwan]
1      1  [macao, taiwan, shanghai]
2      0           [japan, sapporo]
3      0   [sapporo, osaka, taiwan]
4      0  [taiwan, taiwan, sapporo]

In [381]:
t3['body'] = t3['body'].apply(lambda x: [stemmer.stem(y) for y in x])
t3.head()

label                        body
0      1  [send, us, your, password]
1      0    [send, us, your, review]
2      0    [review, your, password]
3      1                [review, us]
4      1      [send, your, password]

In [382]:
t1['body'] = t1['body'].apply(lambda x: ' '.join(x))
t1.head()

label                              body
0      1                chines beij chines
1      1            chines chines shanghai
2      1                      chines macao
3      0                tokyo japan chines
4      1  chines chines chines tokyo japan

In [383]:
t2['body'] = t2['body'].apply(lambda x: ' '.join(x))
t2.head()

label                   body
0      1          taipei taiwan
1      1  macao taiwan shanghai
2      0          japan sapporo
3      0   sapporo osaka taiwan
4      0  taiwan taiwan sapporo

In [384]:
t3['body'] = t3['body'].apply(lambda x: ' '.join(x))
t3.head()

label                   body
0      1  send us your password
1      0    send us your review
2      0   review your password
3      1              review us
4      1     send your password

In [399]:
from sklearn.feature_extraction.text import CountVectorizer
counts_vect = CountVectorizer()#(token_pattern = r"(?u)\b\w+\b")
counts13_1 = counts_vect.fit_transform(t1['body'])
print counts13_1


  (0, 0)	1
  (0, 1)	2
  (1, 4)	1
  (1, 1)	2
  (2, 3)	1
  (2, 1)	1
  (3, 2)	1
  (3, 5)	1
  (3, 1)	1
  (4, 2)	1
  (4, 5)	1
  (4, 1)	3


In [386]:
counts13_10 = counts_vect.fit_transform(t2['body'])
print counts13_10

  (0, 6)	1
  (0, 5)	1
  (1, 4)	1
  (1, 1)	1
  (1, 6)	1
  (2, 3)	1
  (2, 0)	1
  (3, 2)	1
  (3, 3)	1
  (3, 6)	1
  (4, 3)	1
  (4, 6)	2


In [387]:
countsIAML = counts_vect.fit_transform(t3['body'])
print countsIAML

  (0, 2)	1
  (0, 6)	1
  (0, 5)	1
  (0, 4)	1
  (1, 3)	1
  (1, 6)	1
  (1, 5)	1
  (1, 4)	1
  (2, 3)	1
  (2, 2)	1
  (2, 6)	1
  (3, 3)	1
  (3, 5)	1
  (4, 2)	1
  (4, 6)	1
  (4, 4)	1
  (5, 0)	1
  (5, 6)	1
  (5, 5)	1
  (5, 4)	1
  (6, 1)	1
  (6, 3)	1
  (6, 5)	1


# Splitting the data

In [388]:
from sklearn.model_selection import train_test_split
x_train13_1, x_test13_1, y_train13_1, y_test13_1 = train_test_split(counts13_1, t1['label'], test_size=0.2, shuffle=False)
x_train13_10, x_test13_10, y_train13_10, y_test13_10 = train_test_split(counts13_10, t2['label'], test_size=0.2, shuffle=False)
x_trainIAML, x_testIAML, y_trainIAML, y_testIAML = train_test_split(countsIAML, t3['label'], test_size=1, shuffle=False)

# Training the models

In [389]:
from sklearn.naive_bayes import MultinomialNB
model13_1 = MultinomialNB().fit(x_train13_1, y_train13_1)
model13_10 = MultinomialNB().fit(x_train13_10, y_train13_10)
modelIAML = MultinomialNB().fit(x_trainIAML, y_trainIAML)

# Testing the models

In [390]:
predicted13_1 = model13_1.predict(x_test13_1)
predicted13_10 = model13_10.predict(x_test13_10)
predictedIAML = modelIAML.predict(x_testIAML)

# Results

In [392]:
print("Table 13.1 (1 in China, 0 not in China)")
print("Accuracy: %.2f %%" % (np.mean(predicted13_1 == y_test13_1) * 100), "Class prediction: %d" % predicted13_1)
print("Table 13.10 (1 in China, 0 not in China)")
print("Accuracy: %.2f %%" % (np.mean(predicted13_10 == y_test13_10) * 100), "Class prediction: %d" % predicted13_10)
print("Table IAML (0 ham - 1 spam)")
print("Accuracy: %.2f %%" % (np.mean(predictedIAML == y_testIAML) * 100), "Class prediction: %d" % predictedIAML)

Table 13.1 (1 in China, 0 not in China)
('Accuracy: 100.00 %', 'Class prediction: 1')
Table 13.10 (1 in China, 0 not in China)
('Accuracy: 100.00 %', 'Class prediction: 0')
Table IAML (0 ham - 1 spam)
('Accuracy: 100.00 %', 'Class prediction: 0')


# Probabilities (from sklearn - predict_proba)

In [398]:
prob13_1 = model13_1.predict_proba(x_test13_1)
prob13_10 = model13_10.predict_proba(x_test13_10)
probIAML = modelIAML.predict_proba(x_testIAML)
print prob13_1
print prob13_10
print probIAML

[[0.31024139 0.68975861]]
[[0.57142857 0.42857143]]
[[0.52228412 0.47771588]]


# Why are the probabilities obtained with the predict_proba from sklearn different of the probabilities obtained by hand?

The probabilities are different given that predict_proba normalizes them.